// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ClaimsLibrary.Models
{
    [Table("ICC_TRANS")]
    public partial class IccTran
    {
        [Key]
        [Column("ID")]
        public double Id { get; set; }
        [Column("TR_SSN")]
        public double? TrSsn { get; set; }
        [Column("TR_ALL_DONE")]
        [StringLength(255)]
        public string TrAllDone { get; set; }
        [Column("TR_BYE")]
        public double? TrBye { get; set; }
        [Column("TR_CHANGE_PIN_IND")]
        [StringLength(255)]
        public string TrChangePinInd { get; set; }
        [Column("TR_CLAIM_FO")]
        public double? TrClaimFo { get; set; }
        [Column("TR_COMPLETE_TIME", TypeName = "datetime")]
        public DateTime? TrCompleteTime { get; set; }
        [Column("TR_HRS_WORKED")]
        public double? TrHrsWorked { get; set; }
        [Column("TR_IC_AC_RO_IND")]
        [StringLength(255)]
        public string TrIcAcRoInd { get; set; }
        [Column("TR_IP_ADDRESS")]
        [StringLength(255)]
        public string TrIpAddress { get; set; }
        [Column("TR_IVR_CODE")]
        [StringLength(255)]
        public string TrIvrCode { get; set; }
        [Column("TR_LANGUAGE_CODE")]
        [StringLength(255)]
        public string TrLanguageCode { get; set; }
        [Column("TR_LAST_ACTIVITY_TIME", TypeName = "datetime")]
        public DateTime? TrLastActivityTime { get; set; }
        [Column("TR_MF_IND")]
        [StringLength(255)]
        public string TrMfInd { get; set; }
        [Column("TR_NEW_HIRE_IND")]
        [StringLength(255)]
        public string TrNewHireInd { get; set; }
        [Column("TR_PIN")]
        public double? TrPin { get; set; }
        [Column("TR_PIN_TRY_NUM")]
        public double? TrPinTryNum { get; set; }
        [Column("TR_Q1A_ON_CERT")]
        public double? TrQ1aOnCert { get; set; }
        [Column("TR_Q1B_ON_CERT")]
        public double? TrQ1bOnCert { get; set; }
        [Column("TR_Q1C_ON_CERT")]
        public double? TrQ1cOnCert { get; set; }
        [Column("TR_Q2_ON_CERT")]
        public double? TrQ2OnCert { get; set; }
        [Column("TR_Q3A_ON_CERT")]
        public double? TrQ3aOnCert { get; set; }
        [Column("TR_Q3B_ON_CERT")]
        public double? TrQ3bOnCert { get; set; }
        [Column("TR_Q3C_ON_CERT")]
        public double? TrQ3cOnCert { get; set; }
        [Column("TR_Q4_ON_CERT")]
        public double? TrQ4OnCert { get; set; }
        [Column("TR_QUIT_CODE")]
        public double? TrQuitCode { get; set; }
        [Column("TR_RTW_DATE")]
        [StringLength(255)]
        public string TrRtwDate { get; set; }
        [Column("TR_SAT_DATE", TypeName = "datetime")]
        public DateTime? TrSatDate { get; set; }
        [Column("TR_START_TIME", TypeName = "datetime")]
        public DateTime? TrStartTime { get; set; }
        [Column("TR_TRANS_TYPE")]
        [StringLength(255)]
        public string TrTransType { get; set; }
        [Column("TR_WAGES_EARNED")]
        public double? TrWagesEarned { get; set; }
        [Column("TR_WEEK_CLAIMED")]
        public double? TrWeekClaimed { get; set; }
        [Column("TR_WEEK_END_DATE")]
        public double? TrWeekEndDate { get; set; }
        [Column("TR_WORK_SEARCH_IND")]
        public double? TrWorkSearchInd { get; set; }
        [Column("TR_EB_CONTACT_1")]
        [StringLength(255)]
        public string TrEbContact1 { get; set; }
        [Column("TR_EB_CONTACT_2")]
        [StringLength(255)]
        public string TrEbContact2 { get; set; }
        [Column("TR_EB_CONTACT_3")]
        [StringLength(255)]
        public string TrEbContact3 { get; set; }
        [Column("TR_EB_DATE_1")]
        public double? TrEbDate1 { get; set; }
        [Column("TR_EB_DATE_2")]
        public double? TrEbDate2 { get; set; }
        [Column("TR_EB_DATE_3")]
        [StringLength(255)]
        public string TrEbDate3 { get; set; }
        [Column("TR_EB_EMPLOYER_1")]
        [StringLength(255)]
        public string TrEbEmployer1 { get; set; }
        [Column("TR_EB_EMPLOYER_2")]
        [StringLength(255)]
        public string TrEbEmployer2 { get; set; }
        [Column("TR_EB_EMPLOYER_3")]
        [StringLength(255)]
        public string TrEbEmployer3 { get; set; }
        [Column("TR_EB_LOCATION_1")]
        [StringLength(255)]
        public string TrEbLocation1 { get; set; }
        [Column("TR_EB_LOCATION_2")]
        [StringLength(255)]
        public string TrEbLocation2 { get; set; }
        [Column("TR_EB_LOCATION_3")]
        [StringLength(255)]
        public string TrEbLocation3 { get; set; }
        [Column("TR_EB_TYPE_WORK_1")]
        [StringLength(255)]
        public string TrEbTypeWork1 { get; set; }
        [Column("TR_EB_TYPE_WORK_2")]
        [StringLength(255)]
        public string TrEbTypeWork2 { get; set; }
        [Column("TR_EB_TYPE_WORK_3")]
        [StringLength(255)]
        public string TrEbTypeWork3 { get; set; }
        [Column("TR_EB_ADDTL")]
        [StringLength(255)]
        public string TrEbAddtl { get; set; }
        [Column("TR_LAST_WEEK_CLAIMED")]
        public double? TrLastWeekClaimed { get; set; }
        [Column("TR_LAST_REFERER")]
        [StringLength(255)]
        public string TrLastReferer { get; set; }
        [Column("TR_LAST_SCREEN")]
        [StringLength(255)]
        public string TrLastScreen { get; set; }
        [Column("TR_PROGRAM_END_WEEK")]
        public double? TrProgramEndWeek { get; set; }
        [Column("TR_LAST_RESTART_WEEK")]
        public double? TrLastRestartWeek { get; set; }
        [Column("TR_LAST_ERROR")]
        [StringLength(255)]
        public string TrLastError { get; set; }
        [Column("TR_IP_COUNTRY_CODE")]
        [StringLength(255)]
        public string TrIpCountryCode { get; set; }
        [Column("TR_Q3_4T_ON_CERT")]
        public double? TrQ34tOnCert { get; set; }
        [Column("TR_Q4_4T_ON_CERT")]
        public double? TrQ44tOnCert { get; set; }
        [Column("TR_Q5_4T_ON_CERT")]
        public double? TrQ54tOnCert { get; set; }
        [Column("TR_MENUTRAN_ID")]
        [StringLength(255)]
        public string TrMenutranId { get; set; }
        [Column("TR_EB_RESULT_1")]
        [StringLength(255)]
        public string TrEbResult1 { get; set; }
        [Column("TR_EB_RESULT_2")]
        [StringLength(255)]
        public string TrEbResult2 { get; set; }
        [Column("TR_EB_RESULT_3")]
        [StringLength(255)]
        public string TrEbResult3 { get; set; }
        [Column("TR_ACTIVITY_DATE_1")]
        public double? TrActivityDate1 { get; set; }
        [Column("TR_ACTIVITY_DATE_2")]
        public double? TrActivityDate2 { get; set; }
        [Column("TR_ACTIVITY_DATE_3")]
        public double? TrActivityDate3 { get; set; }
        [Column("TR_ACTIVITY_DESCR_1")]
        [StringLength(255)]
        public string TrActivityDescr1 { get; set; }
        [Column("TR_ACTIVITY_DESCR_2")]
        [StringLength(255)]
        public string TrActivityDescr2 { get; set; }
        [Column("TR_ACTIVITY_DESCR_3")]
        [StringLength(255)]
        public string TrActivityDescr3 { get; set; }
        [Column("TR_TLO_EXCEPTION_FLAG")]
        [StringLength(255)]
        public string TrTloExceptionFlag { get; set; }
        [Column("TR_UNION_EXCEPTION_FLAG")]
        [StringLength(255)]
        public string TrUnionExceptionFlag { get; set; }
        [Column("TR_TLO_UNION_PRECHECK_FLAG")]
        [StringLength(255)]
        public string TrTloUnionPrecheckFlag { get; set; }
    }
}