// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ClaimsLibrary.Models
{
    [Table("OCS_MESSAGES")]
    public partial class OcsMessage
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ACTIVE_FLAG")]
        public string ActiveFlag { get; set; }
        [Column("OCS_DB_FIELD_NAME")]
        public string OcsDbFieldName { get; set; }
        [Column("OCS_FORM_FIELD_NAME")]
        public string OcsFormFieldName { get; set; }
        [Column("OCS_FORM_FIELD_ORDER", TypeName = "decimal(18, 0)")]
        public decimal? OcsFormFieldOrder { get; set; }
        [Column("OCS_LANG_CODE")]
        public string OcsLangCode { get; set; }
        [Column("OCS_MAIN_FRAME_MATCH")]
        public string OcsMainFrameMatch { get; set; }
        [Column("OCS_MESSAGE_TXT")]
        public string OcsMessageTxt { get; set; }
        [Column("OCS_MESSAGE_TYPE_CODE")]
        public string OcsMessageTypeCode { get; set; }
        [Column("OCSMSGCD_CODE")]
        public string OcsmsgcdCode { get; set; }
        [Column("OCS_REQUIRED_FLAG")]
        public string OcsRequiredFlag { get; set; }
        [Column("OCS_TEMPLATE_NAME")]
        public string OcsTemplateName { get; set; }
        [Column("OCS_TEMPLATE_TITLE")]
        public string OcsTemplateTitle { get; set; }
        [Column("START_DATE")]
        public DateTime? StartDate { get; set; }
        [Column("END_DATE")]
        public DateTime? EndDate { get; set; }
        [Column("OCS_FORM_FIELD_TYPE")]
        public string OcsFormFieldType { get; set; }
        [Column("OCS_SCREEN_NAME")]
        public string OcsScreenName { get; set; }
        [Column("CORRECT_ANSWER_FLAG")]
        public string CorrectAnswerFlag { get; set; }
    }
}