// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClaimsLibrary.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace ClaimsLibrary.Data
{
    public class IccTranConfiguration : IEntityTypeConfiguration<IccTran>
    {
        public void Configure(EntityTypeBuilder<IccTran> entity)
        {
            entity.Property(e => e.TrLastActivityTime).HasDefaultValueSql("(getdate())");
        }
    }
}
