// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClaimsLibrary.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace ClaimsLibrary.Data
{
    public class OcsMessageConfiguration : IEntityTypeConfiguration<OcsMessage>
    {
        public void Configure(EntityTypeBuilder<OcsMessage> entity)
        {
            entity.Property(e => e.ActiveFlag).HasDefaultValueSql("((0))");

            entity.Property(e => e.CorrectAnswerFlag).HasDefaultValueSql("(N'N')");

            entity.Property(e => e.OcsLangCode).HasDefaultValueSql("(N'EN')");
        }
    }
}
