USE [master]
GO
/****** Object:  Database [Reservations]    Script Date: 3/21/2021 9:04:23 AM ******/
CREATE DATABASE [Reservations]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Reservations', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Reservations.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Reservations_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Reservations_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Reservations] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Reservations].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Reservations] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Reservations] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Reservations] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Reservations] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Reservations] SET ARITHABORT OFF 
GO
ALTER DATABASE [Reservations] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Reservations] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Reservations] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Reservations] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Reservations] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Reservations] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Reservations] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Reservations] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Reservations] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Reservations] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Reservations] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Reservations] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Reservations] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Reservations] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Reservations] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Reservations] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Reservations] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Reservations] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Reservations] SET  MULTI_USER 
GO
ALTER DATABASE [Reservations] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Reservations] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Reservations] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Reservations] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Reservations] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Reservations] SET QUERY_STORE = OFF
GO
USE [Reservations]
GO
/****** Object:  Table [dbo].[SeatTable]    Script Date: 3/21/2021 9:04:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SeatTable](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Row] [nvarchar](max) NULL,
	[Number] [int] NULL,
	[Available] [bit] NOT NULL,
 CONSTRAINT [PK_SeatTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[SeatTable] ON 
GO
INSERT [dbo].[SeatTable] ([Id], [Row], [Number], [Available]) VALUES (1, N'A', 1, 1)
GO
INSERT [dbo].[SeatTable] ([Id], [Row], [Number], [Available]) VALUES (2, N'A', 2, 0)
GO
INSERT [dbo].[SeatTable] ([Id], [Row], [Number], [Available]) VALUES (3, N'B', 1, 0)
GO
INSERT [dbo].[SeatTable] ([Id], [Row], [Number], [Available]) VALUES (4, N'B', 2, 1)
GO
SET IDENTITY_INSERT [dbo].[SeatTable] OFF
GO
USE [master]
GO
ALTER DATABASE [Reservations] SET  READ_WRITE 
GO
